name: TagHelper
version: 1.0.0
description: A library for modifying the displayed name in Minecraft.
author: Comphenix
website: http://www.comphenix.net/TagHelper

main: com.comphenix.taghelper.TagHelperMod
database: false